version: '3.9'

services:
  webapi:
    build:
      context: ./provider
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - /app
    environment:
      - ASPNETCORE_ENVIRONMENT=Test
      - ASPNETCORE_URLS=http://webapi:80
  integrationtests:
    build:
      context: ./consumers
      dockerfile: Dockerfile.test
    volumes:
      - /app
    command: ["dotnet", "test", "--logger", "console;verbosity=normal" ]
    environment:
      - MY_SERVICE_URL=http://webapi:80
    depends_on:
      - webapi

  # test:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.test
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - app
  # mountebank:
  #   image: docker.io/bbyars/mountebank:latest
  #   ports:
  #     - "2525:2525"
  #     - "8080:8080"
  #   volumes:
  #     - ./mountebank/imposters:/imposters
  #   # command: ["start", "--configfile", "/imposters/proxy-to-realserver.json"]
  #   command: ["start", "--configfile", "/imposters/response.json"]
  # test:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.test
  #   volumes:
  #     - .:/app
  #   working_dir: /app
  #   command: ["dotnet", "test", "--logger", "console;verbosity=normal" ]
  #   environment:
  #     - MY_SERVICE_URL=http://mountebank:8080
  #   depends_on:
  #     - mountebank
    # depends_on:
    #   - app
