version: '3.9'

services:
  webapi:
    build:
      context: ./provider
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - /app
    environment:
      - ASPNETCORE_ENVIRONMENT=Test
      - ASPNETCORE_URLS=http://webapi:80
  integrationtests:
    build:
      context: ./consumers
      dockerfile: Dockerfile.test
    volumes:
      - /app
    command: ["dotnet", "test", "--logger", "console;verbosity=normal" ]
    environment:
      - MY_SERVICE_URL=http://webapi:80
    depends_on:
      - webapi
