FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.sln ./


# Copy everything else and build
COPY . ./
RUN dotnet restore
RUN dotnet build

# # Run tests
# ENTRYPOINT ["dotnet", "test", "--logger:trx"]
