name: consumer test

on:
  push:
    paths:
    - '.github/workflows/consumer.yml'
    - 'consumers/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build and test with Docker Compose
      run: |
        docker-compose up --abort-on-container-exit --exit-code-from integrationtests
