name: consumer test

on:
  push:
    paths:
    - 'consumers/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x' # Replace with the version of .NET Core SDK you are using

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./consumers

    - name: Build project
      run: dotnet build --configuration Release
      working-directory: ./consumers

    - name: Run tests
      run: dotnet test --configuration Release
      working-directory: ./consumers
